### ISSUE TITLE
ST: Finalise Project Specification and Timeline with Milestone Descriptions

### ISSUE THREAD

**Issue by exclowd** [BoostGSoC21/ublas#12]
Describe the Project in the Wiki and add Milestones. Update the Project Board with the Milestones. As mentioned in from discussion [here](https://github.com/BoostGSoC21/ublas/discussions/10#discussion-3391752)
The following subtasks need to be done:
- [x] describe the project in the wiki
- [x] describe why the project is needed in Boost.uBlas
- [x] mention/describe milestones (one milestone for each phase) that you have mentioned/described
- [x] describe what the definition of done is for each of the milestones.

**Comment by exclowd** [comment]
- [x] Improve the project desciption
